# Generated by Django 2.2.5 on 2019-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
