# Generated by Django 2.2.5 on 2019-11-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_doctor',
        ),
    ]
